server:
  port: 8082
  address: 0.0.0.0
  servlet:
    context-path: /api/v1

spring:
  application:
    name: mintmey-backend
  
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/mintmey_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    
    # Connection Pool
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: MintMeySecretKey2024ForJWTTokenGeneration
  expiration: 86400000 # 24 hours in milliseconds

# File Upload Configuration
file:
  upload:
    dir: uploads/
    
# CORS Configuration
cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  
# Logging
logging:
  level:
    com.sixammart: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
